export const carDatabase = {
    "Audi": ["A1", "A3 Sedan", "A3 Sportback", "A4", "A5", "A6", "A7", "A8", "Q3", "Q5", "Q7", "Q8", "e-tron", "e-tron GT", "RS3", "RS4", "RS5", "RS6", "RS7", "RS Q3", "RS Q8", "TT", "R8"],
    "BMW": ["Série 1", "Série 2", "Série 3", "Série 4", "Série 5", "Série 6", "Série 7", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4", "i3", "iX", "iX3", "i4", "M2", "M3", "M4", "M5"],
    "BYD": ["Dolphin", "Dolphin Mini", "Seal", "Yuan Plus", "Song Plus", "Tan", "Han"],
    "Caoa Chery": ["iCar", "Tiggo 2", "Tiggo 3x", "Tiggo 5x", "Tiggo 7", "Tiggo 8", "Arrizo 5", "Arrizo 6", "QQ"],
    "Chevrolet": ["Onix", "Onix Plus", "Tracker", "Spin", "Equinox", "Trailblazer", "S10", "Montana", "Cruze", "Cruze Sport6", "Camaro", "Corvette", "Bolt", "Silverado", "Captiva", "Malibu", "Prisma", "Celta", "Classic", "Cobalt", "Agile", "Meriva", "Zafira", "Vectra", "Astra", "Omega", "Kadett", "Monza", "Chevette"],
    "Citroën": ["C3", "C3 Aircross", "C4 Cactus", "C4 Lounge", "C4 Pallas", "C5", "DS3", "DS4", "DS5", "Jumpy", "Xsara Picasso", "C3 Picasso", "Aircross", "C4 VTR"],
    "Dodge": ["Journey", "Ram 2500", "Ram 1500", "Ram 3500", "Dakota", "Durango", "Challenger", "Charger"],
    "Fiat": ["Mobi", "Argo", "Cronos", "Pulse", "Fastback", "Strada", "Toro", "Fiorino", "Ducato", "Uno", "Palio", "Palio Weekend", "Siena", "Grand Siena", "Punto", "Linea", "Bravo", "Stilo", "Marea", "Tempra", "Tipo", "Oggi", "147", "Doblo", "Idea", "Freemont", "500"],
    "Ford": ["Ka", "Ka Sedan", "Fiesta", "Focus", "Ecosport", "Fusion", "Edge", "Bronco Sport", "Maverick", "Ranger", "Mustang", "Territory", "F-150", "F-250", "Courier", "Escort", "Versailles", "Del Rey", "Corcel"],
    "GWM": ["Haval H6", "Ora 03"],
    "Honda": ["City", "City Hatch", "Civic", "HR-V", "ZR-V", "CR-V", "Fit", "WR-V", "Accord", "Pilot", "Civic Si", "NSX"],
    "Hyundai": ["HB20", "HB20S", "Creta", "Tucson", "ix35", "Santa Fe", "Palisade", "Ioniq 5", "Kona", "Azera", "Sonata", "Elantra", "i30", "Veloster", "Veracruz", "HR"],
    "JAC": ["J2", "J3", "J5", "J6", "T40", "T50", "T60", "T80", "E-JS1", "E-JS4", "iEV20", "iEV40"],
    "Jeep": ["Renegade", "Compass", "Commander", "Grand Cherokee", "Wrangler", "Gladiator", "Cherokee"],
    "Kia": ["Picanto", "Rio", "Cerato", "Soul", "Stonic", "Niro", "Sportage", "Sorento", "Carnival", "Mohave", "Cadenza", "Optima", "K2500"],
    "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar", "Freelander"],
    "Lexus": ["UX", "NX", "RX", "ES", "LS"],
    "Mercedes-Benz": ["Classe A", "Classe B", "Classe C", "Classe E", "Classe S", "CLA", "CLS", "GLA", "GLB", "GLC", "GLE", "GLS", "G-Class", "EQA", "EQB", "EQC", "EQE", "EQS", "Sprinter", "Vito"],
    "Mini": ["Cooper", "Cooper S", "Clubman", "Countryman"],
    "Mitsubishi": ["Lancer", "ASX", "Outlander", "Eclipse Cross", "Pajero", "Pajero TR4", "Pajero Sport", "Pajero Full", "L200 Triton", "L200 Outdoor"],
    "Nissan": ["March", "Versa", "V-Drive", "Sentra", "Kicks", "Frontier", "Leaf", "Tiida", "Livina", "Grand Livina"],
    "Peugeot": ["206", "207", "208", "307", "308", "408", "508", "2008", "3008", "5008", "RCZ", "Partner", "Expert", "Boxer", "Hoggar"],
    "Porsche": ["718 Boxster", "718 Cayman", "911", "Taycan", "Panamera", "Macan", "Cayenne"],
    "Ram": ["Classic", "1500", "2500", "3500", "Rampage"],
    "Renault": ["Kwid", "Sandero", "Logan", "Stepway", "Duster", "Oroch", "Captur", "Master", "Zoe", "Megane E-Tech", "Kangoo", "Fluence", "Symbol", "Clio", "Megane", "Scenic"],
    "Subaru": ["Impreza", "XV", "Crosstrek", "Forester", "Outback", "Legacy", "WRX"],
    "Suzuki": ["Jimny", "Jimny Sierra", "Vitara", "Grand Vitara", "S-Cross", "Swift"],
    "Toyota": ["Etios", "Yaris", "Yaris Sedan", "Corolla", "Corolla Cross", "Camry", "Prius", "RAV4", "Hilux", "SW4", "Fielder", "Bandeirante"],
    "Troller": ["T4"],
    "Volkswagen": ["Gol", "Voyage", "Saveiro", "Parati", "Santana", "Polo", "Virtus", "Nivus", "T-Cross", "Taos", "Tiguan", "Jetta", "Passat", "Golf", "Fox", "SpaceFox", "CrossFox", "Up!", "Amarok", "Touareg", "Fusca", "Kombi", "Beetle", "Bora", "New Beetle"],
    "Volvo": ["C30", "C40", "S60", "S90", "V40", "V60", "XC40", "XC60", "XC90", "EX30", "EX90"]
};
