export const carDatabase = {
    "Acura": ["ILX", "Integra", "MDX", "NSX", "RDX", "RLX", "TLX", "ZDX"],
    "Alfa Romeo": ["Giulia", "Stelvio", "Tonale", "4C Spider"],
    "Audi": ["A1", "A3", "A4", "A5", "A6", "A7", "A8", "Q3", "Q5", "Q7", "Q8", "e-tron", "e-tron GT", "RS3", "RS4", "RS5", "RS6", "RS7", "RS Q3", "RS Q8", "TT", "R8"],
    "BMW": ["Série 1", "Série 2", "Série 3", "Série 4", "Série 5", "Série 6", "Série 7", "Série 8", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4", "i3", "i4", "iX", "iX1", "iX3", "i7", "M2", "M3", "M4", "M5", "M8"],
    "BYD": ["Dolphin", "Dolphin Mini", "Seal", "Song Plus", "Yuan Plus", "Tan", "Han", "King", "Shark"],
    "Caoa Chery": ["Tiggo 2", "Tiggo 3x", "Tiggo 5x", "Tiggo 7", "Tiggo 8", "Arrizo 5", "Arrizo 6", "iCar", "QQ"],
    "Chevrolet": ["Onix", "Onix Plus", "Tracker", "S10", "Cruze", "Cruze Sport6", "Spin", "Equinox", "Trailblazer", "Camaro", "Corvette", "Montana", "Bolt", "Silverado", "Captiva", "Cobalt", "Prisma", "Celta", "Classic", "Agile", "Meriva", "Zafira", "Sonic", "Malibu", "Omega", "Blazer", "Astra", "Vectra", "Opala", "Chevette"],
    "Citroën": ["C3", "C3 Aircross", "C4 Cactus", "C4 Lounge", "C4 Picasso", "Grand C4 Picasso", "Jumpy", "Berlingo", "DS3", "DS4", "DS5", "Xsara Picasso", "C3 Picasso", "Aircross"],
    "Dodge": ["Journey", "Ram 1500", "Ram 2500", "Ram 3500", "Ram Classic", "Rampage", "Durango", "Challenger", "Charger"],
    "Ferrari": ["296 GTB", "SF90 Stradale", "F8 Tributo", "Roma", "Portofino", "812 Superfast", "Purosangue", "488", "458", "California"],
    "Fiat": ["Strada", "Mobi", "Argo", "Cronos", "Pulse", "Fastback", "Toro", "Fiorino", "Ducato", "500e", "Titano", "Scudo", "Uno", "Palio", "Siena", "Grand Siena", "Punto", "Bravo", "Linea", "Idea", "Doblo", "Weekend", "Stilo", "Marea", "Tempra", "Tipo", "147"],
    "Ford": ["Ranger", "Maverick", "Bronco Sport", "Mustang", "Mustang Mach-E", "Territory", "Transit", "F-150", "Ka", "Ka Sedan", "Fiesta", "Focus", "EcoSport", "Fusion", "Edge", "Courier", "F-250", "Escort", "Versailles", "Del Rey", "Corcel"],
    "GWM": ["Haval H6", "Ora 03"],
    "Honda": ["Civic", "HR-V", "City Hatch", "City Sedan", "CR-V", "ZR-V", "Accord", "Fit", "WR-V", "Civic Type R", "Prelude"],
    "Hyundai": ["HB20", "HB20S", "Creta", "Tucson", "Santa Fe", "Palisade", "Ioniq 5", "Kona", "HR", "ix35", "Azera", "Elantra", "Sonata", "Veloster", "i30", "Vera Cruz"],
    "JAC": ["E-JS1", "E-JS4", "E-J7", "T40", "T50", "T60", "T80", "J2", "J3", "J5", "J6"],
    "Jaguar": ["E-Pace", "F-Pace", "I-Pace", "F-Type", "XE", "XF", "XJ"],
    "Jeep": ["Renegade", "Compass", "Commander", "Wrangler", "Gladiator", "Grand Cherokee", "Cherokee"],
    "Kia": ["Sportage", "Stonic", "Niro", "Carnival", "Bongo", "Cerato", "Sorento", "Picanto", "Soul", "Mohave", "Optima", "Cadenza"],
    "Land Rover": ["Defender 90", "Defender 110", "Defender 130", "Discovery", "Discovery Sport", "Range Rover", "Range Rover Evoque", "Range Rover Velar", "Range Rover Sport"],
    "Lexus": ["ES", "LS", "NX", "RX", "UX", "RZ"],
    "Mercedes-Benz": ["Classe A", "Classe B", "Classe C", "Classe E", "Classe S", "CLA", "GLA", "GLB", "GLC", "GLE", "GLS", "Classe G", "EQA", "EQB", "EQC", "EQE", "EQS", "Vito", "Sprinter", "AMG GT", "SL"],
    "Mini": ["Cooper", "Cooper S", "Countryman", "Clubman", "John Cooper Works"],
    "Mitsubishi": ["L200 Triton", "Pajero Sport", "Eclipse Cross", "Outlander", "ASX", "Lancer", "Pajero Full", "Pajero TR4"],
    "Nissan": ["Kicks", "Versa", "Sentra", "Frontier", "Leaf", "March", "V-Drive", "Tiida", "Livina", "Grand Livina"],
    "Peugeot": ["208", "e-208", "2008", "e-2008", "3008", "5008", "Partner Rapid", "Expert", "Boxer", "206", "207", "307", "308", "408", "RCZ"],
    "Porsche": ["911", "Cayenne", "Macan", "Panamera", "Taycan", "718 Boxster", "718 Cayman"],
    "Ram": ["Ram 1500", "Ram 2500", "Ram 3500", "Ram Classic", "Rampage"],
    "Renault": ["Kwid", "Stepway", "Logan", "Sandero", "Duster", "Oroch", "Master", "Megane E-Tech", "Kangoo", "Captur", "Fluence", "Clio", "Symbol", "Scenic"],
    "Subaru": ["Forester", "XV", "Outback", "Impreza", "WRX"],
    "Suzuki": ["Jimny Sierra", "Jimny", "Vitara", "S-Cross", "Grand Vitara", "Swift"],
    "Tesla": ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"],
    "Toyota": ["Corolla", "Corolla Cross", "Hilux", "Yaris Hatch", "Yaris Sedan", "SW4", "RAV4", "Camry", "Prius", "Supra", "Etios", "Fielder", "Bandeirante"],
    "Troller": ["T4"],
    "Volkswagen": ["Gol", "Polo", "Virtus", "T-Cross", "Nivus", "Jetta", "Passat", "Tiguan", "Amarok", "Saveiro", "Up!", "Fox", "Golf", "Taos", "ID.4", "ID.Buzz", "Voyage", "SpaceFox", "Parati", "Santana", "Fusca", "Kombi", "Beetle", "Touareg"],
    "Volvo": ["XC40", "XC60", "XC90", "C40", "EX30", "EX90", "S60", "S90", "V40", "V60"]
};
